# apiVersion: v1
# kind: Service
# metadata:
#   name: nats
#   labels:
#     app: nats
# spec:
#   selector:
#     app: nats
#   clusterIP: None
#   ports:
#   - name: client
#     port: 4222
#   - name: cluster
#     port: 6222
#   - name: monitor
#     port: 8222
#   - name: metrics
#     port: 7777
#   - name: leafnodes
#     port: 7422
---
apiVersion: v1
kind: Service
metadata:
  name: nats-test
spec:
  type: ExternalName
  externalName: nats-test.default.svc.cluster.local